#!/data/data/com.termux/files/usr/bin/bash

cd ~/labmusic/Zeromusic || exit

echo "🔄 Syncing with GitHub..."

git pull origin Alpha

git add -u

echo -n "📝 Enter commit message: "
read msg

git commit -m "$msg"

git push origin Alpha

echo "✅ Sync complete!"
